### ISSUE TITLE
`make kind` does not create $HOME/.kube/kubeadmiral/kubeconfig.yaml as expected

### ISSUE THREAD

**Issue by xiaopei-yuan** [kubewharf/kubeadmiral#53]
I followed the [quick start](https://github.com/kubewharf/kubeadmiral/blob/main/docs/quickstart.md#3-bootstrap-kubernetes-clusters) doc, in step 3("Bootstrap Kubernetes clusters") of the prerequisites session, I run `make kind` command, everything went well, but no "$HOME/.kube/kubeadmiral/kubeconfig.yaml" file generated as expected, as bellows:

```
% KUBECONFIG=$HOME/.kube/kubeadmiral/kubeconfig.yaml kubectl config get-clusters

W0504 15:22:12.931407   22785 loader.go:223] Config not found: /Users/bytedance/.kube/kubeadmiral/kubeconfig.yaml
NAME

% ls -l $HOME/.kube/kubeadmiral/kubeconfig.yaml
ls: /Users/bytedance/.kube/kubeadmiral/kubeconfig.yaml: No such file or directory


% ls -l $HOME/.kube/kubeadmiral/

total 64
-rw-------  1 bytedance  staff  5586  5  4 11:44 kubeadmiral-host.yaml
-rw-------  1 bytedance  staff  5610  5  4 11:43 kubeadmiral-member-1.yaml
-rw-------  1 bytedance  staff  5606  5  4 11:44 kubeadmiral-member-2.yaml
-rw-------  1 bytedance  staff  5606  5  4 11:44 kubeadmiral-member-3.yaml
```

**Comment by SOF3** [comment]
The generated kubeconfigs have recently been separated to multiple files. Now it should be `$HOME/.kube/kubeadmiral/kubeadmiral-host.yaml` instead.

Looks like we forgot to update the kubeconfig path in https://github.com/kubewharf/kubeadmiral/blob/main/docs/quickstart.md#5-wait-for-member-clusters-to-be-joined
