### ISSUE TITLE
Env vars HOST_CLUSTER_KUBECONFIG and HOST_CLUSTER_CONTEXT was not defined before in quick start

### ISSUE THREAD

**Issue by xiaopei-yuan** [kubewharf/kubeadmiral#55]
In quickstart ["Source the kubeconfig of the host cluster"](https://github.com/kubewharf/kubeadmiral/blob/main/docs/quickstart.md#1-source-the-kubeconfig-of-the-host-cluster), shall I define HOST_CLUSTER_KUBECONFIG and HOST_CLUSTER_CONTEXT in my bash profile manually?

**Comment by gary-lgy** [comment]
![20230504-160606](https://user-images.githubusercontent.com/44059321/236146060-962416a9-c5c4-4794-97b4-38b9289f46df.png)

HOST_CLUSTER_KUBECONFIG and HOST_CLUSTER_CONTEXT are meant to be replaced with the actual values of the host cluster. There's no need to modify your shell profile :) 

If you reached this step right after following the "Installation" section, HOST_CLUSTER_KUBECONFIG should be `$HOME/.kube/kubeadmiral/kubeadmiral-host.yaml` and HOST_CLUSTER_CONTEXT should be `kind-kubeadmiral-host`.
